/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <string.h>
#include <stdio.h>
#include <string.h>
#include "communicate.h"

#define MAXSUBSCRIBERS 5
#define MAXSTRING 120

typedef struct SubNode
{
    char *ip[15];
    int port;
    char *subscriptions[100];
    struct SubNode *next;
} SubNode;

typedef struct SubList
{
    int size;
    struct SubNode *front, *rear;
    unsigned capacity;
} SubList;

static SubList *subscriberList;

void setup_list(int cap);
bool_t add_subscriber(char *ip, int port);
bool_t remove_subscriber(char *ip, int port);

bool_t *
joinserver_1_svc(char *IP, int ProgID, int ProgVers,  struct svc_req *rqstp)
{
	static bool_t  result;

    // TODO: Later

	return &result;
}

bool_t *
leaveserver_1_svc(char *IP, int ProgID, int ProgVers,  struct svc_req *rqstp)
{
	static bool_t  result;

    // TODO later

	return &result;
}

bool_t *
join_1_svc(char *IP, int Port,  struct svc_req *rqstp)
{
	static bool_t  result;

    if (subscriberList == NULL)
    {
        setup_list(MAXSUBSCRIBERS);
    }

    result = add_subscriber(IP, Port);

    printf("Added client. Result: %d, IP: %s, Port: %d\n", result, IP, Port);

	return &result; 
}

bool_t *
leave_1_svc(char *IP, int Port,  struct svc_req *rqstp)
{
	static bool_t  result;
    
    printf("Leaving...\n");

    result = remove_subscriber(IP, Port);

    printf("Left...\n");

    if(result)
        printf("Removed client. Result: %d, IP: %s, Port: %d\n", result, IP, Port);
    else
        printf("Failed to remove client. Result: %d, IP: %s, Port: %d\n", result, IP, Port);

	return &result;
}

bool_t *
subscribe_1_svc(char *IP, int Port, char *Article,  struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
unsubscribe_1_svc(char *IP, int Port, char *Article,  struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
publish_1_svc(char *Article, char *IP, int Port,  struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
publishserver_1_svc(char *Article, char *IP, int Port,  struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ping_1_svc(struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void setup_list(int cap)
{
    SubList *l = (SubList*)malloc(sizeof(SubList));
    l->capacity = cap;
    l->size = 0;

    subscriberList = l;
}

bool_t add_subscriber(char *ip, int port)
{
    SubNode *n = (SubNode*)malloc(sizeof(SubNode));
    strcpy(*(n->ip), ip);
    n->port = port;

    if(subscriberList->size > 0)
    {
        subscriberList->rear->next = n;
        subscriberList->rear = n;
    }
    else 
    {
        subscriberList->front = n;
        subscriberList->rear = n;
    }

    subscriberList->size = subscriberList->size + 1;

    return 1;

    //TODO ensure there are no duplicates?
}

bool_t remove_subscriber(char *ip, int port)
{
    printf("remove_subscriber1\n");
    SubNode *f = subscriberList->front;
    SubNode *n = f->next;
    printf("remove_subscriber2\n");

    if (!strcmp(*(f->ip), ip) && f->port == port)
    {
        printf("remove_subscriber3\n");
        subscriberList->front = n;
        subscriberList->size = subscriberList->size - 1;
        printf("Changed front and resized\n");
        free(f);
        printf("remove_subscriber4\n");
        return 1;
    }
    while(n)
    {
        if (!strcmp(*(n->ip), ip) && n->port == port)
        {
            f->next = n->next;
            subscriberList->size = subscriberList->size - 1;
            free(n);
            return 1;
        }
    }

    return 0;

}

