/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include "communicate.h"

#define SERVER "127.0.0.1"
#define PORT 8888

CLIENT *setup_rpc(char *host);
int setup_udp();

struct sockaddr_in si_server, si_me;

bool_t join(CLIENT *clnt, char *ip, int port);
bool_t leave(CLIENT *clnt, char *ip, int port);

void *udp_thread_func(void *udp_args);
void *rcp_thread_func(void *rcp_args);

int
main (int argc, char *argv[])
{
    int sock;
    CLIENT *clnt;
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    // clnt = setup_rpc(host);

    //sock = setup_udp();


//    int r = join(clnt, "192.168.1.1", 8888);

#ifndef	DEBUG
//	clnt_destroy (clnt);
#endif	 /* DEBUG */

    exit (0);
}

CLIENT *setup_rpc(char *host)
{
    CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, COMMUNICATE_PROG, COMMUNICATE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    return clnt;
}

int setup_udp()
{
    printf("setup udp\n");
    fflush(stdout);
    int sock;

    if((sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)) == -1) {
        clnt_pcreateerror("socket");
        exit(1);
    }

    printf("memsets\n");
    fflush(stdout);

    memset((char *) &si_server, 0, sizeof(si_server));
    memset((char *) &si_me, 0, sizeof(si_server));

    printf("setup sockets\n");
    fflush(stdout);

    si_server.sin_family = AF_INET;
    si_server.sin_port = htons(PORT);

    si_me.sin_family = AF_INET;
    si_me.sin_addr.s_addr = htonl(INADDR_ANY);
    si_me.sin_port = htons(0);

    printf("creating server\n");
    fflush(stdout);

    if (inet_aton(SERVER, &si_server.sin_addr) == 0) {
        clnt_pcreateerror("inet_aton");
        exit(1);
    }

    printf("binding\n");
    fflush(stdout);

    if (bind(sock, (struct sockaddr *) &si_me, sizeof(si_me)) < 0) {
        clnt_pcreateerror("bind()");
        exit(1);
    }

    printf("printing\n");
    fflush(stdout);

    socklen_t *slen;

    if (getsockname(sock, (struct sockaddr *)&si_me, slen) < 0) {
        clnt_pcreateerror("getsockname");
        exit(1);
    }

    printf("Bound to IP: %s, PORT: %d", inet_ntoa(si_me.sin_addr), ntohs(si_me.sin_port));
}

void *udp_thread_func(void *udp_args)
{}
void *rcp_thread_func(void *rcp_args)
{}

bool_t join(CLIENT *clnt, char *ip, int port)
{
	bool_t  *result;

	result = join_1(ip, port, clnt);

	if (result == (bool_t *) NULL) {
		clnt_perror (clnt, "Join call failed");
	}

    return *result;
}

bool_t leave(CLIENT *clnt, char *ip, int port)
{
	bool_t  *result;

	result = leave_1(ip, port, clnt);

	if (result == (bool_t *) NULL) {
		clnt_perror (clnt, "Leave call failed");
	}

    return *result;

}


/*
void
communicate_prog_1(char *host)
{
	bool_t  *result_1;
	char *joinserver_1_IP;
	int joinserver_1_ProgID;
	int joinserver_1_ProgVers;
	bool_t  *result_2;
	char *leaveserver_1_IP;
	int leaveserver_1_ProgID;
	int leaveserver_1_ProgVers;
	bool_t  *result_5;
	char *subscribe_1_IP;
	int subscribe_1_Port;
	char *subscribe_1_Article;
	bool_t  *result_6;
	char *unsubscribe_1_IP;
	int unsubscribe_1_Port;
	char *unsubscribe_1_Article;
	bool_t  *result_7;
	char *publish_1_Article;
	char *publish_1_IP;
	int publish_1_Port;
	bool_t  *result_8;
	char *publishserver_1_Article;
	char *publishserver_1_IP;
	int publishserver_1_Port;
	bool_t  *result_9;

	result_1 = joinserver_1(joinserver_1_IP, joinserver_1_ProgID, joinserver_1_ProgVers, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = leaveserver_1(leaveserver_1_IP, leaveserver_1_ProgID, leaveserver_1_ProgVers, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = subscribe_1(subscribe_1_IP, subscribe_1_Port, subscribe_1_Article, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = unsubscribe_1(unsubscribe_1_IP, unsubscribe_1_Port, unsubscribe_1_Article, clnt);
	if (result_6 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = publish_1(publish_1_Article, publish_1_IP, publish_1_Port, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = publishserver_1(publishserver_1_Article, publishserver_1_IP, publishserver_1_Port, clnt);
	if (result_8 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = ping_1(clnt);
	if (result_9 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
}
*/


