/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "communicate.h"

CLIENT *setup_rpc(char *host);

bool_t join(CLIENT *clnt, char *ip, int port);
bool_t leave(CLIENT *clnt, char *ip, int port);
bool_t subscribe(CLIENT *clnt, char *ip, int port, char *Article);
bool_t unsubscribe(CLIENT *clnt, char *ip, int port, char *Article);
bool_t publish(CLIENT *clnt, char *ip, int port, char *Article);

int
main (int argc, char *argv[])
{
    CLIENT *clnt;
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    
    clnt = setup_rpc(host);

    int r = join(clnt, "192.168.1.1", 8888);

    printf("Join Result: %d\n", r);

    r = join(clnt, "192.168.1.2", 8888);

    printf("Join Result: %d\n", r);

    int s = subscribe(clnt, "192.168.1.1", 8888, "Science;UMN;;");
    
    printf("Subscribe Result: %d\n", s);
    
    s = subscribe (clnt, "192.168.1.2", 8888, "English;Hemingway");
    
    printf("Subscribe Result: %d\n", s);

    int p = publish (clnt, "192.168.1.1", 8888, "Food;MasterChef;Ramsay;cake");
 
    printf("Publish Result: %d\n", p);

    p = publish (clnt, "192.168.1.2", 8888, "Sports;NFL;Brady;;");

    printf("Publish Result: %d\n", p);

    int u = unsubscribe (clnt, "192.168.1.2", 8888, "English");

    printf("Unsubscribe Result: %d\n", u);
    
    u = unsubscribe (clnt, "192.168.1.1", 8888, "UMN");

    printf("Unsubscribe Result: %d\n", u);

    u = unsubscribe (clnt, "192.168.1.2", 8888, "Hemingway");

    printf("Unsubscribe Result: %d\n", u);

    r = leave(clnt, "255.255.255.255", 8888);

    printf("Leave Result: %d\n", r);

    r = leave(clnt, "192.168.1.1", 8888);

    printf("Leave Result: %d\n", r);

    r = leave(clnt, "192.168.1.2", 8888);

    printf("Leave Result: %d\n", r);
    
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

    exit (0);
}

CLIENT *setup_rpc(char *host)
{
    CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, COMMUNICATE_PROG, COMMUNICATE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    return clnt;
}

bool_t join(CLIENT *clnt, char *ip, int port)
{
	bool_t  *result;

	result = join_1(ip, port, clnt);

	if (result == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}

    return *result;
}

bool_t leave(CLIENT *clnt, char *ip, int port)
{
	bool_t  *result;

	result = leave_1(ip, port, clnt);

	if (result == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}

    return *result;

}

bool_t subscribe(CLIENT *clnt, char *ip, int port, char *Article)
{
	bool_t *result; 

	result = subscribe_1(ip, port, Article, clnt);

	if (result == (bool_t *) NULL) {
                clnt_perror (clnt, "call failed");
        }

	return *result;

}

bool_t unsubscribe(CLIENT *clnt, char *ip, int port, char *Article) 
{

	bool_t *result; 

	result = unsubscribe_1(ip, port, Article, clnt);
	if (result == (bool_t *) NULL) 
	{
		clnt_perror (clnt, "call failed");
	} 

	return *result;
}

bool_t publish(CLIENT *clnt, char *ip, int port, char *Article)
{
	bool_t *result;
	result = publish_1(Article, ip, port, clnt);
	if (result == (bool_t *) NULL) 
	{
		clnt_perror (clnt, "call failed");
	}

	return *result;
}
/*
void
communicate_prog_1(char *host)
{
	bool_t  *result_1;
	char *joinserver_1_IP;
	int joinserver_1_ProgID;
	int joinserver_1_ProgVers;
	bool_t  *result_2;
	char *leaveserver_1_IP;
	int leaveserver_1_ProgID;
	int leaveserver_1_ProgVers;
	bool_t  *result_5;
	char *subscribe_1_IP;
	int subscribe_1_Port;
	char *subscribe_1_Article;
	bool_t  *result_6;
	char *unsubscribe_1_IP;
	int unsubscribe_1_Port;
	char *unsubscribe_1_Article;
	bool_t  *result_7;
	char *publish_1_Article;
	char *publish_1_IP;
	int publish_1_Port;
	bool_t  *result_8;
	char *publishserver_1_Article;
	char *publishserver_1_IP;
	int publishserver_1_Port;
	bool_t  *result_9;

	result_1 = joinserver_1(joinserver_1_IP, joinserver_1_ProgID, joinserver_1_ProgVers, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = leaveserver_1(leaveserver_1_IP, leaveserver_1_ProgID, leaveserver_1_ProgVers, clnt);
	if (result_2 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = subscribe_1(subscribe_1_IP, subscribe_1_Port, subscribe_1_Article, clnt);
	if (result_5 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = unsubscribe_1(unsubscribe_1_IP, unsubscribe_1_Port, unsubscribe_1_Article, clnt);
	if (result_6 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = publish_1(publish_1_Article, publish_1_IP, publish_1_Port, clnt);
	if (result_7 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = publishserver_1(publishserver_1_Article, publishserver_1_IP, publishserver_1_Port, clnt);
	if (result_8 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = ping_1(clnt);
	if (result_9 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
}
*/


