/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <string.h>
#include <stdio.h>
#include <string.h>
#include "communicate.h"

#define MAXSUBSCRIBERS 5
#define MAXSTRING 120

typedef struct ClientNode
{
    char *ip;
    int port;
    char *subscriptions[100];
    struct ClientNode *next;
} ClientNode;

static ClientNode *clientList;
static int numSubs = 0;


void setup_list(int cap);
void list_subscribers();
void print_sub(ClientNode *n);
bool_t add_subscriber(char *ip, int port);
bool_t remove_subscriber(char *ip, int port);

bool_t *
join_1_svc(char *IP, int Port,  struct svc_req *rqstp)
{
	static bool_t  result;

    result = add_subscriber(IP, Port);

    printf("Added client. Result: %d, IP: %s, Port: %d\n", result, IP, Port);

    //TODO DELETE THIS DEBUGGING
    list_subscribers();

	return &result; 
}

bool_t *
leave_1_svc(char *IP, int Port,  struct svc_req *rqstp)
{
	static bool_t  result;
    
    result = remove_subscriber(IP, Port);

    if(result)
        printf("Removed client. Result: %d, IP: %s, Port: %d\n", result, IP, Port);
    else
        printf("Failed to remove client. Result: %d, IP: %s, Port: %d\n", result, IP, Port);

    list_subscribers();

	return &result;
}

bool_t *
subscribe_1_svc(char *IP, int Port, char *Article,  struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
unsubscribe_1_svc(char *IP, int Port, char *Article,  struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
publish_1_svc(char *Article, char *IP, int Port,  struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
ping_1_svc(struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

/**
bool_t *
joinserver_1_svc(char *IP, int ProgID, int ProgVers,  struct svc_req *rqstp)
{
	static bool_t  result;

    // TODO: Later

	return &result;
}

bool_t *
leaveserver_1_svc(char *IP, int ProgID, int ProgVers,  struct svc_req *rqstp)
{
	static bool_t  result;

    // TODO later

	return &result;
}

bool_t *
publishserver_1_svc(char *Article, char *IP, int Port,  struct svc_req *rqstp)
{
	static bool_t  result;

    // TODO

	return &result;
}
*/


bool_t add_subscriber(char *ip, int port)
{
    if(numSubs >= MAXSUBSCRIBERS){
        return 0;
    }

     ClientNode*n = ( ClientNode*)malloc(sizeof( ClientNode));
    
    n->ip = malloc(strlen(ip) * sizeof(char));
    strcpy(n->ip, ip);
    n->port = port;
    n->next = NULL;

    if(clientList == NULL){
        clientList = n;
        numSubs++;
        return 1;
    }
     ClientNode*current = clientList ;
    while(current->next != NULL){
        current = current->next;
    }
    
    current->next = n;
    numSubs++;
    return 1;

    //TODO ensure there are no duplicates?
}

bool_t remove_subscriber(char *ip, int port)
{
    ClientNode *current = clientList ;

    if (!strcmp(current->ip, ip) && current->port == port)
    {
        clientList = current->next;
        free(current->ip);
        free(current);
        numSubs--;
        return 1;
    }

    ClientNode *tmp;
    int i;

    for(i = 0; i < numSubs-1; i++)
    {
        tmp = current;
        current = current->next;
        if (!strcmp(current->ip, ip) && current->port == port)
        {
            tmp->next = current->next;
            free(current->ip);
            free(current);
            numSubs--;
            return 1;
        }
    }

    return 0;

}

void print_sub(ClientNode *n)
{
    printf("IP: %s, Port: %d\n", n->ip, n->port);
}

void list_subscribers()
{
    ClientNode *n = clientList ;
    while(n != NULL)
    {
        print_sub(n);
        n = n->next;
    }
}

