/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include "communicate.h"
#include "udp.h"

#define MAXSTRING 120

#define SERVER "127.0.0.1"
int server_port = 8888;

char *my_ip = "127.0.0.1";
int my_port = -1;

struct sockaddr_in my_addr, server_addr;
int my_sock;

CLIENT *setup_rpc(char *host);
int setup_udp();

void *ping_thread_func(void *ping_args);
void *rpc_thread_func(void *rpc_args);
void *udp_thread_func(void *udp_args);

int live = 1;

bool_t join(CLIENT *clnt, char *ip, int port);
bool_t leave(CLIENT *clnt, char *ip, int port);
bool_t subscribe(CLIENT *clnt, char *ip, int port, char *Article);
bool_t unsubscribe(CLIENT *clnt, char *ip, int port, char *Article);
bool_t publish(CLIENT *clnt, char *ip, int port, char *Article);

CLIENT *clnt;

int
main (int argc, char *argv[])
{
    char *host;
    pthread_t rpc_thread, udp_thread, ping_thread;

    if (argc < 2) {
        printf ("usage: %s server_host\n", argv[0]);
        exit (1);
    }
    host = argv[1];

    my_sock = setup_udp();
    clnt = setup_rpc(host);

    pthread_create(&udp_thread, NULL, udp_thread_func, NULL);
    pthread_create(&rpc_thread, NULL, rpc_thread_func, NULL);
    pthread_create(&ping_thread, NULL, ping_thread_func, (void *)clnt);

    while(live){}

    pthread_join(udp_thread, NULL);
    pthread_join(rpc_thread, NULL);
    pthread_join(ping_thread, NULL);

    /** TEMPORARY TESTING CALLS 
    printf("All threads joined\n Program terminating\n");;

    int r = join(clnt, "192.168.1.1", 8888);

    printf("Join Result: %d\n", r);

    r = join(clnt, "192.168.1.2", 8888);

    printf("Join Result: %d\n", r);

    int s = subscribe(clnt, "192.168.1.1", 8888, "Science;UMN;;");

    printf("Subscribe Result: %d\n", s);

    s = subscribe (clnt, "192.168.1.2", 8888, "English;Hemingway");

    printf("Subscribe Result: %d\n", s);

    int p = publish (clnt, "192.168.1.1", 8888, "Food;MasterChef;Ramsay;cake");

    printf("Publish Result: %d\n", p);

    p = publish (clnt, "192.168.1.2", 8888, "Sports;NFL;Brady;;");

    printf("Publish Result: %d\n", p);

    int u = unsubscribe (clnt, "192.168.1.2", 8888, "English");

    printf("Unsubscribe Result: %d\n", u);

    u = unsubscribe (clnt, "192.168.1.1", 8888, "UMN");

    printf("Unsubscribe Result: %d\n", u);

    u = unsubscribe (clnt, "192.168.1.2", 8888, "Hemingway");

    printf("Unsubscribe Result: %d\n", u);

    int s = subscribe(clnt, "127.0.0.1", 8888, "Science;UMN;;");
    int p = publish (clnt, "127.0.0.1", 1234, "Science;NatGeo;Tyson;moon");

    r = leave(clnt, "255.255.255.255", 8888);

    printf("Leave Result: %d\n", r);

    r = leave(clnt, "192.168.1.1", 8888);

    printf("Leave Result: %d\n", r);

    r = leave(clnt, "192.168.1.2", 8888);

    printf("Leave Result: %d\n", r);
    */

#ifndef	DEBUG
    clnt_destroy (clnt);
#endif	 /* DEBUG */

    exit (0);
}

CLIENT *setup_rpc(char *host)
{
    CLIENT *clnt;

#ifndef	DEBUG
    clnt = clnt_create (host, COMMUNICATE_PROG, COMMUNICATE_VERSION, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror (host);
        exit (1);
    }
#endif	/* DEBUG */

    if(join(clnt, my_ip, my_port))
        printf("Successfully joined server.\n");
    else
        printf("Server join failed.\n");

    return clnt;
}

int setup_udp() {
    int s;

    memset((char *)&server_addr, '\0', sizeof(server_addr));

    server_addr.sin_family = AF_INET;
    server_addr.sin_port = htons(server_port);

    if(inet_aton(SERVER, &server_addr.sin_addr) == 0){
        fprintf(stderr, "inet_aton() failed in udp_thread\n");
        exit(1);
    }

    InitServer(0, &s, &my_addr);

    if (connect(s, (struct sockaddr *)&server_addr, sizeof(server_addr)) < 0){
        printf("Error connecting\n");
        return false;
    }

    int slen = sizeof(my_addr);

    if (getsockname(s, (struct sockaddr *)&my_addr, &slen) < 0){
        printf("Error connecting\n");
        return false;
    }

    my_port = ntohs(my_addr.sin_port);
    printf("Client Initialized\n %s %d\n", inet_ntoa(my_addr.sin_addr), ntohs(my_addr.sin_port));
    return s;
}

bool_t join(CLIENT *clnt, char *ip, int port)
{
    bool_t  *result;

    printf("Joining: %s:%d", ip, port);
    result = join_1(ip, port, clnt);

    if (result == (bool_t *) NULL) {
        clnt_perror (clnt, "call failed");
    }

    return *result;
}

bool_t leave(CLIENT *clnt, char *ip, int port)
{
    bool_t  *result;

    result = leave_1(ip, port, clnt);

    if (result == (bool_t *) NULL) {
        clnt_perror (clnt, "call failed");
    }

    return *result;

}

bool_t subscribe(CLIENT *clnt, char *ip, int port, char *Article)
{
    bool_t *result; 

    result = subscribe_1(ip, port, Article, clnt);

    if (result == (bool_t *) NULL) {
        clnt_perror (clnt, "call failed");
    }

    return *result;

}

bool_t unsubscribe(CLIENT *clnt, char *ip, int port, char *Article) 
{

    bool_t *result; 

    result = unsubscribe_1(ip, port, Article, clnt);
    if (result == (bool_t *) NULL) 
    {
        clnt_perror (clnt, "call failed");
    } 

    return *result;
}

bool_t publish(CLIENT *clnt, char *ip, int port, char *Article)
{
    bool_t *result;
    result = publish_1(Article, ip, port, clnt);
    if (result == (bool_t *) NULL) 
    {
        clnt_perror (clnt, "call failed");
    }

    return *result;
}

void *rpc_thread_func(void *rpc_args)
{
    int menu_choice;
    while(live)
    {
        char article[120];
        printf("Welcome!\n%s\n%s\n%s\n%s\n%s\n%s",
                "What do you want to do?",
                "1 - subscribe",
                "2 - unsubscribe",
                "3 - publish",
                "4 - quit",
                "> ");
        scanf("%d", &menu_choice);
        switch(menu_choice) {
            case 1:                     //Subscribe
                printf("Subscribe to what?\n> ");
                scanf("%s", article);
                if(subscribe(clnt, my_ip, my_port, article))
                    printf("Subscribe successful!\n");
                else
                    printf("Subscribe unsuccessful!\n");
                break;

            case 2:                     //Unsubscribe
                printf("Unsubscribe from what?\n> ");
                scanf("%s", article);
                if(unsubscribe(clnt, my_ip, my_port, article))
                    printf("Unsubscribe successful!\n");
                else
                    printf("Unsubscribe unsuccessful!\n");
                break;
            case 3:
                printf("What's the article?\n> ");
                scanf("%s", article);
                if(publish(clnt, my_ip, my_port, article))
                    printf("Publish successful!\n");
                else
                    printf("Publish unsuccessful!\n");
                break;
            case 4:
                live = 0;
                break;
            default:
                printf("I don't recognize that input\n");
                break;
        }
    }
}

void *ping_thread_func(void *ping_args)
{
    CLIENT *clnt = (CLIENT *)ping_args;
    bool_t *result;

    while(live){
        result = ping_1(clnt);
        printf("Sending Ping\n");
        if (result == (bool_t *) NULL) {
            clnt_perror(clnt, "Ping failed");
            live = 0;
        }
        printf("Ping Received\n");

        sleep(60);
    }
}

void *udp_thread_func(void *udp_args)
{

    while(1){

        char buffer[MAXSTRING];

        int len = RecvFrom(my_sock, &server_addr, buffer);
        printf("waiting\n");
        if (len) {
            printf("%s\n", buffer);
        } else {
            printf("UDP Live\n");
        }
    }
}
